language: java
dist: trusty
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "./test-repo"
env:
  global:
  - secure: pSe/4X4KI3vXNMs9dB28Ezf2iouU7QXQeXUcF5lhsyguhrYkaohsStBFkdRN6wxcmaR8wW5fCejJv5HBc8p6vV8GcjXLOPBCIScqY+556wSMwE+BXnpEj5/eNlgLBnWZFAh0lqnM9NdkdWjtfN3EmOOuMWRQozsoA7kDpIMmJql9Oif9Pj8Vf04OdjwFBR/9nEp/fwl7s9+z2CY5Pq+QxnNEnYk0dJDtQmiOiVEnta1ExvFg+iKB/N18Ohur6dzqKM0GBrIpRxYphdsAYpz+yQvXg3u4BO7MlP49Y5zhjmEccevQ+jeTHllpdTPvXv+IQjmWmFNEAWJWaB9iVNYGcPwwrinxAHzYeau9//0HISAUnP1qbrx958a2XZ1qgyeB2vGnlL39El9FW9hh4UGsVXA/NWLkDVk3WZlLUPAbidLiv67d33kdQe9ZqFPf4gT1LctM9McJQqE7+PoXv+Wpjf/h2wSph17PF9SBZD+ZzqroPpNmV2jPnkDf8XnVJeyZN4P22zGWyb0BNn+n9WS05mjTMxgXZRNmUJK6yTMmkCb77Kq8jMuMZtTkSSQlVgvm3c9rxEalGCw6FoDwRGGsdiipCXKr2OTVR6F+n1dYVedWUku6mm96GFM9JHK6h1iXRzxUpqTEfSjDquSnuBjYMet3NtouEv4yu40rp3/t0J4=
  - secure: hb8Ti+zgNFqii0SL8korKHYCYkmoz20D5Elqo9uGgnfhupVqXKWMHZWvsA0vV+Yev0V+MzOmhxA81UnUY0lpwjXMQs1YbHscrmiHJOPLrU+W/t5E91Pq2ztrvycREWbWwOdp6ltRomLmt72hNDdsiAGuLZ+QqysMjgLxVtzDhVd/H8ynli10+3TgoODTWrkl2wl0V+bb7vm0bvGo2Q29GAeu0NRZXN+NnIn0ZHNdguiO2EMpeRQzjGs8MetENllt+7HBk+I3XY0+tByBRyRmL24XU0yfpbHUmj58JxBPIHqWVcJoO/AFmPu0JSfci7SwgnYZ87wxuXVS8Bi+piUUq/qdoo+a++c4fN2nM5dyRTrC6DBucmb0McOtz4w1nHdKAWa/n56UTOGQfE+boGvpXuvliVQFXjNqh2Ve82a1RbQZpPdDE8YAy8vs7R57wK5hdvWCMt9t3eVNnwZ7sLmSWLF3/TxmIjsG4CkUbvnfQYCXraEyLr0Ehkk2WslrzAeQNaW/5Slhzr9v8rT3HRcqp2Jx9fYH852Jp+70pdIeRHsPURHytlrYZErd4bLNCj2L0sxD7AgFyL8Nytw05FtoEN8+ggJif3jDNqIWtbIIkalB6tx55uJwlGBd5d/rqiXhGcBO/neV1Orm5OaznocX3SYrIgOiF5LeBdzHf3WegXk=
install:
- "/bin/true"
script:
- "/bin/cp -f ./.mvn/ci/settings.xml $HOME/.m2/settings.xml"
- "/bin/cp -f ./.mvn/ci/toolchains.xml $HOME/.m2/toolchains.xml"
- "./.mvn/verify.sh || exit 1"
- "./.mvn/release-bintray.sh || exit 1"
